; NEOLINK V1 — PlatformIO configuration
; Hardware: ESP32-S3 Waveshare Touch LCD 3.5"
; Fase 1: Sensores (SHT35 + MAX31865) via Serial

[env:neolink_v1]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

; Flash & PSRAM
board_build.arduino.memory_type = qio_opi
board_upload.flash_size          = 16MB
board_build.partitions           = default_16MB.csv

; Monitor
monitor_speed  = 115200
monitor_filters = esp32_exception_decoder

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

lib_deps =
    ; Sensores
    adafruit/Adafruit SHT31 Library @ ^2.2.2
    adafruit/Adafruit MAX31865 library @ ^1.5.0
    adafruit/Adafruit BusIO @ ^1.16.1
    ; Comunicación
    bblanchon/ArduinoJson @ ^7.3.1
    ; Display ST7796 (v1.5.5 exacta — v1.5.6+ rompe SPI mode en ST7796)
    moononournation/GFX Library for Arduino @ 1.5.5
    ; I/O Expander TCA9554 (controla CS y RST del LCD)
    robtillaart/TCA9554 @ ^0.1.2
